const fs = require('fs');
const path = require('path');
const { Pool, types } = require('pg');
require('dotenv').config();

/*
 * Legacy SQLite implementation (retained for reference only).
 *
 * const Database = require('better-sqlite3');
 * const DATABASE_FILE = path.join(__dirname, '..', 'data', 'employees.db');
 * const sqlite = new Database(DATABASE_FILE);
 * sqlite.pragma('journal_mode = WAL');
 * sqlite.pragma('foreign_keys = ON');
 *
 * sqlite.exec(`
 *   CREATE TABLE IF NOT EXISTS employees (
 *     id INTEGER PRIMARY KEY AUTOINCREMENT,
 *     firstName TEXT NOT NULL,
 *     lastName TEXT NOT NULL,
 *     email TEXT NOT NULL UNIQUE,
 *     phone TEXT,
 *     department TEXT,
 *     designation TEXT,
 *     salary REAL,
 *     joinDate TEXT NOT NULL,
 *     status TEXT NOT NULL DEFAULT 'active',
 *     location TEXT,
 *     managerId INTEGER,
 *     avatar TEXT
 *   );
 * `);
 */

const SEED_FILE = path.join(__dirname, '..', 'data', 'employees.json');
types.setTypeParser(1700, Number);

const connection = process.env.DATABASE_URL
  ? { connectionString: process.env.DATABASE_URL }
  : {
      host: process.env.DB_HOST || 'localhost',
      port: Number.parseInt(process.env.DB_PORT, 10) || 5432,
      database: process.env.DB_NAME || 'employee_directory',
      user: process.env.DB_USER || 'postgres',
      password: process.env.DB_PASSWORD
    };
const pool = new Pool({
  ...connection,
  ssl: process.env.DB_SSL === 'true' ? { rejectUnauthorized: false } : false
});

async function seedDatabase(client)
{
  const { rows: [{ count }] } = await client.query(
    'SELECT COUNT(*)::integer AS count FROM employees'
  );

  if (count > 0 || !fs.existsSync(SEED_FILE))
  {
    return;
  }

  const employees = JSON.parse(fs.readFileSync(SEED_FILE, 'utf8'));
  await client.query('BEGIN');

  try
  {
    for (const employee of employees)
    {
      await client.query(`
        INSERT INTO employees (
          id, "firstName", "lastName", email, phone, department, designation,
          salary, "joinDate", status, location, "managerId", avatar
        ) VALUES (
          $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
        )
        ON CONFLICT (id) DO NOTHING
      `, [
        employee.id,
        employee.firstName,
        employee.lastName,
        employee.email,
        employee.phone,
        employee.department,
        employee.designation,
        employee.salary,
        employee.joinDate,
        employee.status,
        employee.location,
        employee.managerId,
        employee.avatar
      ]);
    }

    await client.query(`
      SELECT setval(
        pg_get_serial_sequence('employees', 'id'),
        COALESCE((SELECT MAX(id) FROM employees), 1),
        (SELECT COUNT(*) > 0 FROM employees)
      )
    `);
    await client.query('COMMIT');
  }
  catch (error)
  {
    await client.query('ROLLBACK');
    throw error;
  }
}

async function initializeDatabase()
{
  const client = await pool.connect();

  try
  {
    await client.query(`
      CREATE TABLE IF NOT EXISTS employees (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "firstName" TEXT NOT NULL,
        "lastName" TEXT NOT NULL,
        email TEXT NOT NULL UNIQUE,
        phone TEXT,
        department TEXT,
        designation TEXT,
        salary NUMERIC,
        "joinDate" DATE NOT NULL,
        status TEXT NOT NULL DEFAULT 'active',
        location TEXT,
        "managerId" INTEGER,
        avatar TEXT
      );

      CREATE INDEX IF NOT EXISTS idx_employees_department ON employees(department);
      CREATE INDEX IF NOT EXISTS idx_employees_status ON employees(status);
      CREATE INDEX IF NOT EXISTS idx_employees_location ON employees(location);
      CREATE INDEX IF NOT EXISTS idx_employees_join_date ON employees("joinDate");
    `);
    await seedDatabase(client);
  }
  finally
  {
    client.release();
  }
}

const ready = initializeDatabase();

async function query(text, parameters)
{
  await ready;
  return pool.query(text, parameters);
}

module.exports = { query, pool, ready };
